### ISSUE TITLE
Power Storage CBMs Limited to One Each w/No Bionic Slots Enabled

### ISSUE THREAD

**Issue by chriseich21** [Kenan2000/CDDA-Kenan-Modpack#137]
Game Version: Cataclysm-DDA experimental build 2021-07-24-1012
Kenan Version: https://github.com/Kenan2000/CDDA-Kenan-Modpack/commit/11e67d7c0de9806da740e2d0e699a2482fdc2463
New install, fresh world as CRIT Lone Wolf, only UDP Tileset added on top.

Active Mod List:
![image](https://user-images.githubusercontent.com/18540501/126879069-c2250290-c2d2-407f-bbbb-fb5cb99a2979.png)

The Problem:
In inventory
![image](https://user-images.githubusercontent.com/18540501/126886139-1863421c-4cd9-43ad-95e0-659f25d7e756.png)
In activation menu to install (with debug installation)
![image](https://user-images.githubusercontent.com/18540501/126879018-888e25aa-211d-48ac-a056-9d053a98d8da.png)

The highest value I can get (was able to install a second Extra Power Storage after doing the MKII Upgrade)
![image](https://user-images.githubusercontent.com/18540501/126879040-8d726fb6-c556-4625-bb72-00668f9fa4b5.png)
![image](https://user-images.githubusercontent.com/18540501/126879083-e80176ea-d565-4d85-a134-68d5a138eebc.png)

On a separate note, if you see any mods up top you recommend not using let me know :D

**Comment by Kenan2000** [comment]
@chriseich21 Hello there, supposedly, this https://github.com/CleverRaven/Cataclysm-DDA/commit/83bdbb7589b5eb31ff9d3e29c9be5a413a05e894#diff-3d0ef47ac4d216ce9c93d3d4b3b45a113385b5d02d858aa3c513b1a8a2662bd7, makes sure that these work correctly, are you on latest experimental? I've merged another commit thanks to your help https://github.com/Kenan2000/CDDA-Kenan-Modpack/commit/fa7edf3820df3c01a72c57429af539b247893457, here, it adds same functionality to these items in another mod as well

**Comment by chriseich21** [comment]
@Kenan2000 Hey Kenan, sorry I recently started using the modpack and didn't realize it was due to a problem in the base game. I tested the newest CDDA experimental version implementing the commit above, Cataclysm-DDA experimental build 2021-07-25-0740, and it is still a problem in the base game. Using the Extra Power Storage mod with the fix committed in fa7edf3 of Kenan pack also still does not allow duplicate installation.

As it's a problem apparently coming from the base CDDA, I'll close this for now and retest once experimental CDDA allows duplicates again.
