### ISSUE TITLE
Errors making the game crash on loading save, and at random intervals.

### ISSUE THREAD

**Issue by Simhans** [Kenan2000/CDDA-Kenan-Modpack#98]
21:53:54.180 : Starting log.
21:53:54.180 INFO : Cataclysm DDA version c821798
21:53:54.180 INFO : [main] C locale set to C
21:53:54.180 INFO : [main] C++ locale set to C
21:53:54.180 INFO : SDL version used during compile is 2.0.14
21:53:54.180 INFO : SDL version used during linking and in runtime is 2.0.14
21:53:54.252 INFO : Number of render drivers on your system: 5
21:53:54.252 INFO : Render driver: 0/direct3d
21:53:54.252 INFO : Render driver: 1/direct3d11
21:53:54.252 INFO : Render driver: 2/opengl
21:53:54.252 INFO : Render driver: 3/opengles2
21:53:54.252 INFO : Render driver: 4/software
21:53:54.275 INFO : [options] C locale set to C
21:53:54.275 INFO : [options] C++ locale set to C
21:53:54.299 INFO : Active renderer: 0/direct3d
21:53:54.403 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
21:53:54.816 INFO : Setting language to: 'en'
21:53:54.816 INFO : Language is set to: 'en'
21:53:54.816 INFO : [translations] C locale set to Norwegian Bokmål_Norway.1252
21:53:54.816 INFO : [translations] C++ locale set to C
21:53:55.867 WARNING : opendir [./mods/] failed with "No such file or directory".
21:54:42.929 WARNING : opendir [./save/Greater Washington Area/mods] failed with "No such file or directory".
21:55:26.688 INFO : Loaded tileset: UNDEAD_PEOPLE_BASE
21:55:34.295 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part recharge_station has unknown flag REVERSIBLE
21:55:34.915 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part recharge_station has unknown flag TOOL_SCREWDRIVER
21:55:34.915 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part horn_bicycle has unknown flag REVERSIBLE
21:55:34.915 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part horn_bicycle has unknown flag TOOL_SCREWDRIVER
21:55:34.915 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part television has unknown flag TOOL_SCREWDRIVER
21:55:34.915 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part saddle has unknown flag REVERSIBLE
21:55:34.915 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part saddle has unknown flag TOOL_WRENCH
21:55:34.916 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part storage_battery_removable has unknown flag REVERSIBLE
21:55:34.916 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part storage_battery_removable has unknown flag TOOL_NONE
21:55:34.916 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part aisle_lights has unknown flag REVERSIBLE
21:55:34.916 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part aisle_lights has unknown flag TOOL_SCREWDRIVER
21:55:34.917 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part wing_mirror has unknown flag REVERSIBLE
21:55:34.917 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part wing_mirror has unknown flag TOOL_SCREWDRIVER
21:55:34.917 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part frame_handle has unknown flag REVERSIBLE
21:55:34.917 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part roof_cloth has unknown flag NAILABLE
21:55:34.917 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part roof_cloth has unknown flag REVERSIBLE
21:55:34.918 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part distorion_amp_motor_part has unknown flag EMITTER
21:55:34.918 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part nanoboard has unknown flag TOOL_NONE
21:55:34.918 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part nanohalfboard has unknown flag TOOL_NONE
21:55:34.918 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part nanotech_crawler has unknown flag NO_JACK
21:55:34.918 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part nanotech_crawler has unknown flag TRACKED
21:55:34.919 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part minifridge_atomic has unknown flag TOOL_WRENCH
21:55:34.919 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part minifreezer_atomic has unknown flag TOOL_WRENCH
21:55:34.919 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part radio_atomic has unknown flag TOOL_SCREWDRIVER
21:55:34.919 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part television_atomic has unknown flag TOOL_SCREWDRIVER
21:55:34.919 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part tread1 has unknown flag TRACKED
21:55:34.919 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part tread2 has unknown flag TRACKED
21:55:34.920 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part tread3 has unknown flag TRACKED
21:55:34.920 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part gloopletread has unknown flag TRACKED
21:55:34.920 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part oozletread has unknown flag TRACKED
21:55:34.920 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part graytread has unknown flag TRACKED
21:55:34.920 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part frostie_wheel has unknown flag TRACKED
21:55:34.920 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part gloople_tank has unknown flag FUEL_TANK
21:55:34.920 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part gloople_tank_large has unknown flag FUEL_TANK
21:55:34.920 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part gloople_wheel has unknown flag TRACKED
21:55:34.920 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part gray_tank has unknown flag FUEL_TANK
21:55:34.920 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part gray_tank_large has unknown flag FUEL_TANK
21:55:34.920 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part gray_wheel has unknown flag TRACKED
21:55:34.920 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part grinder has unknown flag TRACKED
21:55:34.920 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part oozle_tank has unknown flag FUEL_TANK
21:55:34.920 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part oozle_tank_large has unknown flag FUEL_TANK
21:55:34.920 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part oozle_wheel has unknown flag TRACKED
21:55:34.921 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part frostie_boat_hull has unknown flag TRACKED
21:55:34.921 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part frostie_wheel_sea has unknown flag TRACKED
21:55:34.921 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part wheel_caster_vo has unknown flag NO_JACK
21:55:34.921 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part tank_small_insulated has unknown flag TOOL_WRENCH
21:55:34.921 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part roadheader has unknown flag CRASH_TERRAIN_AROUND
21:55:34.921 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part roadheader has unknown flag ROADHEAD
21:55:35.811 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon bonespear in style Desert Wind doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon gungnir in style Desert Wind doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon mace_plus_one in style Desert Wind doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon mace_plus_two in style Desert Wind doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon morningstar_plus_one in style Desert Wind doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon morningstar_plus_two in style Desert Wind doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon qiang_plus_one in style Desert Wind doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon qiang_plus_two in style Desert Wind doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon rune_biomancer_weapon in style Desert Wind doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon rune_technomancer_weapon in style Desert Wind doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon spear_steel_plus_one in style Desert Wind doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon spear_steel_plus_two in style Desert Wind doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon lizardfolk_trident in style Desert Wind doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon lizardfolk_javelin in style Desert Wind doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon estoc_plus_one in style Diamond Mind doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon estoc_plus_two in style Diamond Mind doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon katana_plus_one in style Diamond Mind doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon katana_plus_two in style Diamond Mind doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon rapier_plus_one in style Diamond Mind doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon rapier_plus_two in style Diamond Mind doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon estoc_plus_one in style Hylian Swordsmanship doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon estoc_plus_two in style Hylian Swordsmanship doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon katana_plus_one in style Hylian Swordsmanship doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon katana_plus_two in style Hylian Swordsmanship doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon arming_sword_plus_one in style Hylian Swordsmanship doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon arming_sword_plus_two in style Hylian Swordsmanship doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon broadsword_plus_one in style Hylian Swordsmanship doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon broadsword_plus_two in style Hylian Swordsmanship doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon flamesword in style Hylian Swordsmanship doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon gram in style Hylian Swordsmanship doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon jian_plus_one in style Hylian Swordsmanship doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon jian_plus_two in style Hylian Swordsmanship doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon khopesh_plus_one in style Hylian Swordsmanship doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon khopesh_plus_two in style Hylian Swordsmanship doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon longsword_plus_one in style Hylian Swordsmanship doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon longsword_plus_two in style Hylian Swordsmanship doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon nodachi_plus_one in style Hylian Swordsmanship doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon nodachi_plus_two in style Hylian Swordsmanship doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon orich_longsword in style Hylian Swordsmanship doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon rune_kelvinist_weapon in style Hylian Swordsmanship doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon sword_xiphos_plus_one in style Hylian Swordsmanship doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon sword_xiphos_plus_two in style Hylian Swordsmanship doesn't exist.
21:55:36.509 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon tanto_plus_one in style Hylian Swordsmanship doesn't exist.
21:55:36.510 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon tanto_plus_two in style Hylian Swordsmanship doesn't exist.
21:55:36.510 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon wakizashi_plus_one in style Hylian Swordsmanship doesn't exist.
21:55:36.510 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon wakizashi_plus_two in style Hylian Swordsmanship doesn't exist.
21:55:36.510 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon zweihander_plus_one in style Hylian Swordsmanship doesn't exist.
21:55:36.510 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon zweihander_plus_two in style Hylian Swordsmanship doesn't exist.
21:55:36.510 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon estoc_plus_one in style Iron Heart doesn't exist.
21:55:36.510 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon estoc_plus_two in style Iron Heart doesn't exist.
21:55:36.510 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon katana_plus_one in style Iron Heart doesn't exist.
21:55:36.510 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon katana_plus_two in style Iron Heart doesn't exist.
21:55:36.510 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon arming_sword_plus_one in style Iron Heart doesn't exist.
21:55:36.510 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon arming_sword_plus_two in style Iron Heart doesn't exist.
21:55:36.510 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon broadsword_plus_one in style Iron Heart doesn't exist.
21:55:36.510 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon broadsword_plus_two in style Iron Heart doesn't exist.
21:55:36.510 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon gram in style Iron Heart doesn't exist.
21:55:36.510 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon jian_plus_one in style Iron Heart doesn't exist.
21:55:36.510 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon jian_plus_two in style Iron Heart doesn't exist.
21:55:36.510 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon longsword_plus_one in style Iron Heart doesn't exist.
21:55:36.510 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon longsword_plus_two in style Iron Heart doesn't exist.
21:55:36.510 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon nodachi_plus_one in style Iron Heart doesn't exist.
21:55:36.510 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon nodachi_plus_two in style Iron Heart doesn't exist.
21:55:36.510 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon orich_longsword in style Iron Heart doesn't exist.
21:55:36.510 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon rune_kelvinist_weapon in style Iron Heart doesn't exist.
21:55:36.510 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon zweihander_plus_one in style Iron Heart doesn't exist.
21:55:36.510 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon zweihander_plus_two in style Iron Heart doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon flamesword in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon khopesh_plus_one in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon khopesh_plus_two in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon sword_xiphos_plus_one in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon sword_xiphos_plus_two in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon tanto_plus_one in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon tanto_plus_two in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon wakizashi_plus_one in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon wakizashi_plus_two in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon i_staff_plus_one in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon i_staff_plus_two in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon knife_combat_plus_one in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon knife_combat_plus_two in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon knife_rambo_plus_one in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon knife_rambo_plus_two in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon kris_plus_one in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon kris_plus_two in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon kukri_plus_one in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon kukri_plus_two in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon laevateinn in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon orich_knife_combat in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon q_staff_plus_one in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon q_staff_plus_two in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon rune_animist_weapon in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon rune_magus_weapon in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon springstaff-extended in style Setting Sun doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon estoc_plus_one in style Shii-Cho doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon estoc_plus_two in style Shii-Cho doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon katana_plus_one in style Shii-Cho doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon katana_plus_two in style Shii-Cho doesn't exist.
21:55:36.511 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon longsword_plus_one in style Shii-Cho doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon longsword_plus_two in style Shii-Cho doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon nodachi_plus_one in style Shii-Cho doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon nodachi_plus_two in style Shii-Cho doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon orich_longsword in style Shii-Cho doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon tanto_plus_one in style Shii-Cho doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon tanto_plus_two in style Shii-Cho doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon wakizashi_plus_one in style Shii-Cho doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon wakizashi_plus_two in style Shii-Cho doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon zweihander_plus_one in style Shii-Cho doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon zweihander_plus_two in style Shii-Cho doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon mace_plus_one in style Stone Dragon doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon mace_plus_two in style Stone Dragon doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon morningstar_plus_one in style Stone Dragon doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon morningstar_plus_two in style Stone Dragon doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon rune_technomancer_weapon in style Stone Dragon doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon estoc_plus_one in style Stone Dragon doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon estoc_plus_two in style Stone Dragon doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon longsword_plus_one in style Stone Dragon doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon longsword_plus_two in style Stone Dragon doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon nodachi_plus_one in style Stone Dragon doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon nodachi_plus_two in style Stone Dragon doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon orich_longsword in style Stone Dragon doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon zweihander_plus_one in style Stone Dragon doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon zweihander_plus_two in style Stone Dragon doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon battleaxe_plus_one in style Stone Dragon doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon battleaxe_plus_two in style Stone Dragon doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon fire_ax_plus_one in style Stone Dragon doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon fire_ax_plus_two in style Stone Dragon doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon orich_fire_ax in style Stone Dragon doesn't exist.
21:55:36.512 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon rune_stormshaper_weapon in style Stone Dragon doesn't exist.
21:55:36.513 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon tanto_plus_one in style Tiger Claw doesn't exist.
21:55:36.513 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon tanto_plus_two in style Tiger Claw doesn't exist.
21:55:36.513 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon knife_combat_plus_one in style Tiger Claw doesn't exist.
21:55:36.513 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon knife_combat_plus_two in style Tiger Claw doesn't exist.
21:55:36.513 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon knife_rambo_plus_one in style Tiger Claw doesn't exist.
21:55:36.513 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon knife_rambo_plus_two in style Tiger Claw doesn't exist.
21:55:36.513 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon kris_plus_one in style Tiger Claw doesn't exist.
21:55:36.513 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon kris_plus_two in style Tiger Claw doesn't exist.
21:55:36.513 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon kukri_plus_one in style Tiger Claw doesn't exist.
21:55:36.513 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon kukri_plus_two in style Tiger Claw doesn't exist.
21:55:36.513 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon orich_knife_combat in style Tiger Claw doesn't exist.
21:55:36.513 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon rune_animist_weapon in style Tiger Claw doesn't exist.
21:55:36.513 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon battleaxe_plus_one in style Tiger Claw doesn't exist.
21:55:36.513 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon battleaxe_plus_two in style Tiger Claw doesn't exist.
21:55:36.513 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon fire_ax_plus_one in style Tiger Claw doesn't exist.
21:55:36.513 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon fire_ax_plus_two in style Tiger Claw doesn't exist.
21:55:36.513 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon orich_fire_ax in style Tiger Claw doesn't exist.
21:55:36.513 ERROR : src/martialarts.cpp:361 [void check_martialarts()] Weapon rune_stormshaper_weapon in style Tiger Claw doesn't exist.

**Comment by Theawesomeboophis** [comment]
The vehicle part undefined errors should be fixed by https://github.com/Kenan2000/CDDA-Kenan-Modpack/pull/96, as for the rest, it seems a mod you're using should have magiclysm as a requirement but doesn't, as all plus weapons are from Magiclysm, can you submit your mod list?

**Comment by Theawesomeboophis** [comment]
Are you using MMA Mods Extension?

**Comment by Theawesomeboophis** [comment]
Are you using MMA Mods Extension? If So, Please try relaunching world with Magiclysm if so.

**Comment by Simhans** [comment]
You're right, i was using the MMA Mods Extension without magiclysm. I enabled magiclysm and that got rid of the warnings, but the game still crashes. I can't find the crash.log in config, only the debug.log, but that seems to be a separate issue. Anyway here is the most recent debug log:

10:27:10.846 : Starting log.
10:27:10.846 INFO : Cataclysm DDA version c821798
10:27:10.856 INFO : [main] C locale set to C
10:27:10.856 INFO : [main] C++ locale set to C
10:27:10.856 INFO : SDL version used during compile is 2.0.14
10:27:10.857 INFO : SDL version used during linking and in runtime is 2.0.14
10:27:11.028 INFO : Number of render drivers on your system: 5
10:27:11.028 INFO : Render driver: 0/direct3d
10:27:11.028 INFO : Render driver: 1/direct3d11
10:27:11.028 INFO : Render driver: 2/opengl
10:27:11.028 INFO : Render driver: 3/opengles2
10:27:11.028 INFO : Render driver: 4/software
10:27:11.053 INFO : [options] C locale set to C
10:27:11.053 INFO : [options] C++ locale set to C
10:27:11.092 INFO : Active renderer: 0/direct3d
10:27:11.279 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
10:27:11.740 INFO : Setting language to: 'en'
10:27:11.740 INFO : Language is set to: 'en'
10:27:11.740 INFO : [translations] C locale set to Norwegian Bokmål_Norway.1252
10:27:11.740 INFO : [translations] C++ locale set to C
10:27:14.672 WARNING : opendir [./mods/] failed with "No such file or directory".
10:28:57.634 ERROR : src/game.cpp:3076 [bool game::load_packs(const string&, const std::vector<string_id<MOD_INFORMATION> >&, loading_ui&)] unknown content spellcraft
10:29:19.544 WARNING : opendir [./save/Greater Washington Area/mods] failed with "No such file or directory".
10:30:06.314 INFO : Loaded tileset: UNDEAD_PEOPLE_BASE
10:30:14.469 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part recharge_station has unknown flag REVERSIBLE
10:30:18.255 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part recharge_station has unknown flag TOOL_SCREWDRIVER
10:30:18.255 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part horn_bicycle has unknown flag REVERSIBLE
10:30:18.256 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part horn_bicycle has unknown flag TOOL_SCREWDRIVER
10:30:18.256 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part television has unknown flag TOOL_SCREWDRIVER
10:30:18.257 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part saddle has unknown flag REVERSIBLE
10:30:18.257 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part saddle has unknown flag TOOL_WRENCH
10:30:18.258 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part storage_battery_removable has unknown flag REVERSIBLE
10:30:18.258 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part storage_battery_removable has unknown flag TOOL_NONE
10:30:18.259 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part aisle_lights has unknown flag REVERSIBLE
10:30:18.259 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part aisle_lights has unknown flag TOOL_SCREWDRIVER
10:30:18.259 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part wing_mirror has unknown flag REVERSIBLE
10:30:18.260 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part wing_mirror has unknown flag TOOL_SCREWDRIVER
10:30:18.261 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part frame_handle has unknown flag REVERSIBLE
10:30:18.261 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part roof_cloth has unknown flag NAILABLE
10:30:18.261 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part roof_cloth has unknown flag REVERSIBLE
10:30:18.263 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part distorion_amp_motor_part has unknown flag EMITTER
10:30:18.263 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part nanoboard has unknown flag TOOL_NONE
10:30:18.264 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part nanohalfboard has unknown flag TOOL_NONE
10:30:18.264 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part nanotech_crawler has unknown flag NO_JACK
10:30:18.264 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part nanotech_crawler has unknown flag TRACKED
10:30:18.265 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part minifridge_atomic has unknown flag TOOL_WRENCH
10:30:18.265 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part minifreezer_atomic has unknown flag TOOL_WRENCH
10:30:18.265 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part radio_atomic has unknown flag TOOL_SCREWDRIVER
10:30:18.266 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part television_atomic has unknown flag TOOL_SCREWDRIVER
10:30:18.266 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part tread1 has unknown flag TRACKED
10:30:18.267 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part tread2 has unknown flag TRACKED
10:30:18.267 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part tread3 has unknown flag TRACKED
10:30:18.267 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part gloopletread has unknown flag TRACKED
10:30:18.267 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part oozletread has unknown flag TRACKED
10:30:18.267 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part graytread has unknown flag TRACKED
10:30:18.267 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part frostie_wheel has unknown flag TRACKED
10:30:18.267 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part gloople_tank has unknown flag FUEL_TANK
10:30:18.267 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part gloople_tank_large has unknown flag FUEL_TANK
10:30:18.267 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part gloople_wheel has unknown flag TRACKED
10:30:18.267 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part gray_tank has unknown flag FUEL_TANK
10:30:18.268 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part gray_tank_large has unknown flag FUEL_TANK
10:30:18.268 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part gray_wheel has unknown flag TRACKED
10:30:18.268 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part grinder has unknown flag TRACKED
10:30:18.268 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part oozle_tank has unknown flag FUEL_TANK
10:30:18.268 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part oozle_tank_large has unknown flag FUEL_TANK
10:30:18.268 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part oozle_wheel has unknown flag TRACKED
10:30:18.271 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part frostie_boat_hull has unknown flag TRACKED
10:30:18.272 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part frostie_wheel_sea has unknown flag TRACKED
10:30:18.272 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part wheel_caster_vo has unknown flag NO_JACK
10:30:18.272 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part tank_small_insulated has unknown flag TOOL_WRENCH
10:30:18.273 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part roadheader has unknown flag CRASH_TERRAIN_AROUND
10:30:18.273 ERROR : src/veh_type.cpp:683 [static void vpart_info::check()] vehicle part roadheader has unknown flag ROADHEAD

And here is my modlist: 
"dda",
  "no_npc_food",
  "package_bionic_professions",
  "BL9_100monres",
  "realdarkskies",
  "sierra_madre",
  "battle_maid",
  "magiclysm",
  "spellcraft",
  "crt_expansion",
  "EngineeringEssentials",
  "bow_opness",
  "More_Survivors_Stories",
  "Nechronica_Redux",
  "PK_REBALANCE",
  "pneumo_fun",
  "mutant_npcs_new",
  "Arcana",
  "psychiclysm",
  "wandering_masters",
  "collectablemod",
  "XEAS",
  "rice",
  "AAA",
  "adv_gear",
  "advtech",
  "ArmUpSurvEx",
  "arsenal_breach",
  "Arts' Guns",
  "Tolerate_This",
  "aftershock",
  "bioco",
  "Bionic_Space_Expander",
  "bio_recipes",
  "Bootleg_Walkers",
  "CBM_Arms",
  "climate_defying_farming",
  "SD_Magcrafting",
  "craftgp",
  "culinary_days_ahead",
  "FIC_Weapons",
  "dried_fruits",
  "ExArch",
  "fallout",
  "Uekibati_mod",
  "growable-pots",
  "Gourmand'sGraces",
  "guncotton",
  "homestead",
  "ew_pack",
  "eps_cbm",
  "Locked_and_Loaded",
  "makeshift",
  "modern_weapon",
  "MST_Extra",
  "nw_pack",
  "NM_wpns",
  "Pix's Shit",
  "futurearmory",
  "beamswordmod",
  "Soy mod",
  "cool_mod",
  "CerealMod",
  "VermilionMod",
  "thermal_ups",
  "blazemod",
  "vorpal_weapons",
  "WildLiving",
  "Xeno_SAS4",
  "GOV_BANDITS",
  "crazy_labs",
  "DinoMod",
  "DracoDogMod",
  "DracoPigMod",
  "jury_rigged_robots",
  "modular_turrets_no_blacklist",
  "mutant_animals",
  "mutant_insects",
  "Salvaged_Robots",
  "light_weariness",
  "alt_map_key",
  "Cata++",
  "ks_variety_pack",
  "diluted_mutagens",
  "even_more_mutations",
  "food_irradiator",
  "mxoudpcosmetics",
  "hydroponics",
  "machine",
  "Mining_Mod",
  "more_survivor_notes",
  "more_survivor_stuff",
  "MMA",
  "MMA_Mods_Extension",
  "Ninja",
  "recruitment_options",
  "zets_hair_extensions_undead",
  "more_locations",
  "morlock_village",
  "oa_early_game_mutations_mod",
  "Ships",
  "water_towers",
  "whaleys_tallbuild",
  "deoxymod",
  "Heavy miners",
  "Tankmod_Revived",
  "AbrahmsRecipes1",
  "Merchant",
  "ProjectKawaii",
  "sarcophagi_access"

**Comment by Simhans** [comment]
I've noticed that the debug.log never includes the actual crashing. I'm trying to find the crash.log but it just isn't showing up in config. I've tried to search for others having the same issue but can't find anyone just missing the whole crash log. 

Some additional info which might help pinpoint the issue, when I first generated the world and made a char I could play just  fine for about 4 hours. The day after when I first loaded the save these issues started appearing. It specifically crashes about one to three minutes after loading when i'm just walking around. Yesterday it also crashed if I didn't move immediately after the loading was done, but this just stopped happening with no direct meddling from me.

It seems that there could be an issue generating new structures or loading new areas, it could also be some type of spawning npc or enemy that breaks the game.

**Comment by Theawesomeboophis** [comment]
Can you try creating a new world with the same settings and test it there, sometimes it's not a problem with the game and is just the world being weird.

**Comment by Simhans** [comment]
Just tried a new world with the same settings, it still crashed in the same way as before. I walked maybe 100 tiles with the char and then CTD.

**Comment by Simhans** [comment]
Here is my CDDA folder: https://drive.google.com/file/d/1k6NKiOFwOe89CNY-nTplVGMTkMbtkRAE/view?usp=sharing
It should be easy enough to reenact, just start a new char on  the "lake city" world which is the newest world and walk around a bit. Also notice the non-existent crash.log in config.

**Comment by Simhans** [comment]
I mainly notice it crashing when I approach a forest, but it happens randomly as well. But to get a guaranteed quick CTD just walk in/around some forest for a little while.

**Comment by Theawesomeboophis** [comment]
Have you tried a complete reinstall of cataclysm?

**Comment by Theawesomeboophis** [comment]
I'm gonna update my download of cataclysm and see if it crashes for me as well.

**Comment by Theawesomeboophis** [comment]
Current Version is b030323, are you using 0.F dev or is your version an old one?

**Comment by Theawesomeboophis** [comment]
Are you using current version, if not, can you update and try again, if none of these methods work, it may be an error with either mods or cataclysm itself.

**Comment by Theawesomeboophis** [comment]
I tried reproducing the error, it didn't crash, a fresh install should fix the problem, if it doesn't, report back.

**Comment by Simhans** [comment]
Yep, did a fresh reinstall of CDDA, this modpack and the tileset and it seems to be running smoothly now. I'll report back if it starts crashing again. Thanks a lot for the help.

**Comment by Theawesomeboophis** [comment]
> Yep, did a fresh reinstall of CDDA, this modpack and the tileset and it seems to be running smoothly now. I'll report back if it starts crashing again. Thanks a lot for the help.

No problem, sometimes the way Cataclysm updates requires complete reinstall to fix what I call "Ghost Errors" or errors that are non-existent, not sure why they happen, but most of the time reinstalling mods or the game fixes them.
